name: Centos 7

on:
  push:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    container: centos:centos7

    steps:
    - name: Update yum
      run: yum update -qqy
    - name: Install requirements 
      run: |
        yum install -yqq openssl wget python3 xz-utils lsb-release sudo dialog apt-utils redhat-lsb subversion chrpath openssl-devel python3-devel
        yum groupinstall -yqq 'Development Tools'
        yum install -yqq centos-release-scl
        yum install -yqq devtoolset-9 llvm-toolset-7
        pip3 install --upgrade pip
    - name: Install latest git
      run: |
        yum -yqq install https://packages.endpointdev.com/rhel/7/os/x86_64/endpoint-repo.x86_64.rpm
        yum install -yqq git
    - uses: actions/checkout@v3
    - name: install rltest
      run: pip3 install RLTest
    - name: Install redis
      run: |
        set -x
        . scl_source enable  devtoolset-9 || true
        . scl_source enable llvm-toolset-7 || true
        git clone https://github.com/redis/redis
        cd redis
        git checkout 7.0.3
        make install
    - name: Install rust
      run: |
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs > install_rust.sh
        sh install_rust.sh -y
    - name: format
      run: $HOME/.cargo/bin/cargo fmt -- --check
    - name: Build
      run: |
        . scl_source enable  devtoolset-9 || true
        . scl_source enable llvm-toolset-7 || true
        $HOME/.cargo/bin/cargo build --verbose
        $HOME/.cargo/bin/cargo build --release --verbose
    - name: Tests
      run: cd pytests;./run_tests.sh
    - name: install ramp packer
      run: pip3 install ramp-packer
    - name: Pack
      run: target/release/packer
      env:
          LC_ALL: en_US.utf-8
          LANG: en_US.utf-8
    - name: Setup s3cmd action
      if: ${{ github.ref_name == 'master' && github.ref_type == 'branch' }}
      uses: s3-actions/s3cmd@v1.2.0
      with:
        provider: aws
        region: us-east-2
        access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    - name: Upload artifacts
      if: ${{ github.ref_name == 'master' && github.ref_type == 'branch' }}
      run: |
        s3cmd put -P target/release/redisgears2-release.linux-rhel.7-x86_64.master.zip s3://redismodules/redisgears/snapshots/
