name: Centos 7

on:
  push:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    container: centos:centos7

    steps:
    - uses: actions/checkout@v3
    - name: Update yum
      run: yum update -qqy
    - name: Install requirements 
      run: |
        yum install -yqq git openssl wget python3 xz-utils lsb-release sudo dialog apt-utils redhat-lsb subversion chrpath openssl-devel python3-devel
        yum groupinstall -yqq 'Development Tools'
        yum install -yqq centos-release-scl
        yum install -yqq devtoolset-9 llvm-toolset-7
        pip3 install --upgrade pip
    - name: install rltest
      run: pip3 install RLTest
    - name: Install redis
      run: |
        set -x
        . scl_source enable  devtoolset-9 || true
        . scl_source enable llvm-toolset-7 || true
        git clone https://github.com/redis/redis
        cd redis
        git checkout 7.0.3
        make install
    - name: Install rust
      run: |
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs > install_rust.sh
        sh install_rust.sh -y
    - name: format
      run: $HOME/.cargo/bin/cargo fmt -- --check
    - name: Build
      run: |
        . scl_source enable  devtoolset-9 || true
        . scl_source enable llvm-toolset-7 || true
        $HOME/.cargo/bin/cargo build --verbose
        $HOME/.cargo/bin/cargo build --release --verbose
    - name: Tests
      run: cd pytests;./run_tests.sh
    - name: install ramp packer
      run: pip3 install git+https://github.com/RedisLabsModules/RAMP@master
    - name: Pack
      run: target/release/packer
      env:
          LC_ALL: en_US.utf-8
          LANG: en_US.utf-8
