name: Ubuntu Latest

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: install rltest
      run: pip install RLTest
    - name: install redis
      run: git clone https://github.com/redis/redis; cd redis; git checkout 7.0.3; make install
    - name: format
      run: cargo fmt -- --check
    - name: Build debug
      run: cargo build --verbose
    - name: Build release
      run: cargo build --release --verbose
    - name: Tests
      run: cd pytests;./run_tests.sh
    - name: install ramp packer
      run: pip install git+https://github.com/RedisLabsModules/RAMP@support_dependency_packing
    - name: Pack
      run: target/release/packer
